application: a-lab-games
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: web/static/image/favicon.ico
  upload: web/static/image/favicon\.ico

- url: /
  static_files: web/test.html
  upload: /
- url: /
  static_dir: web
