application: a-lab-games
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /template
  script: web/template/(.html)

- url: /css
  static_dir: web/static/css

- url: /unity
  static_dir: web/static/unity

- url: /image
  static_dir: web/static/image

- url: /js
  static_dir: web/static/js

- url: /.*
  script: main.py